//
//  UseBiometricsRouter.swift
//  BiometricLogin
//
//  Created by Zaim Ramlan on 26/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UseBiometricsRoutingLogic {
  func routeToUseEmailPassword()
}

protocol UseBiometricsDataPassing {
  var dataStore: UseBiometricsDataStore? { get }
}

class UseBiometricsRouter: NSObject, UseBiometricsRoutingLogic, UseBiometricsDataPassing {
  var viewController: UseBiometricsViewController?
  var dataStore: UseBiometricsDataStore?
  
  // MARK: Routing
  
  func routeToUseEmailPassword() {
    print("Routing to use email & password ...")
  }
}
