//
//  UseBiometricsModels.swift
//  BiometricLogin
//
//  Created by Zaim Ramlan on 26/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UseBiometricsModels {
  
  // MARK: Use Cases
  
  enum UseBiometrics {
    struct Request {
    }

    struct Response {
      var result: BiometricsWorker.AuthenticationResult
    }

    struct ViewModel {
      var result: BiometricsWorker.AuthenticationResult
    }
  }
}
