//
//  UseBiometricsRouter.swift
//  BiometricLogin
//
//  Created by Zaim Ramlan on 26/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UseBiometricsRoutingLogic {
  func routeToBack()
  func routeToUseEmailPassword()
  func routeToDashboard()
}

protocol UseBiometricsDataPassing {
  var dataStore: UseBiometricsDataStore? { get }
}

class UseBiometricsRouter: NSObject, UseBiometricsRoutingLogic, UseBiometricsDataPassing {
  var viewController: UseBiometricsViewController?
  var dataStore: UseBiometricsDataStore?
  
  // MARK: Routing
  
  func routeToBack() {
    viewController?.navigationController?.popToRootViewController(animated: true)
  }
  
  func routeToUseEmailPassword() {
    let destinationVC = UIStoryboard(name: IBConstants.Storyboard.Login, bundle: nil).instantiateViewController(withIdentifier: IBConstants.ViewController.Login.UseEmailPassword)
    viewController?.navigationController?.pushViewController(destinationVC, animated: true)
  }
  
  func routeToDashboard() {
    guard let destinationVC = UIStoryboard(name: IBConstants.Storyboard.Dashboard, bundle: nil).instantiateInitialViewController() else { return }
    viewController?.navigationController?.present(destinationVC, animated: true, completion: nil)
  }
}
