//
//  UseEmailPasswordModels.swift
//  BiometricLogin
//
//  Created by Zaim Ramlan on 25/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UseEmailPasswordModels {

  // MARK: Data Store Fetch
  
  enum FetchFromDataStore {
    struct Request {
    }
    
    struct Response {
      var userAttribute: String
    }
    
    struct ViewModel {
      var userAttribute: String
    }
  }
  
  // MARK: Use Cases
  
  enum UseEmailPassword {
    struct Request {
      var variableToPass: String?
    }

    struct Response {
      var containsErrors: Bool
      var genericErrorMessage: String?
      var variablePassed: VariablePassed?
    }

    struct ViewModel {
      var containsErrors: Bool
      var genericErrorMessage: String?
      var variablePassed: VariablePassed?
    }
  }

  // MARK: View Models

  struct VariablePassed {
    var errorMessage: String?
  }
}
