//
//  UseEmailPasswordRouter.swift
//  BiometricLogin
//
//  Created by Zaim Ramlan on 25/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UseEmailPasswordRoutingLogic {
  func routeToSomewhere()
}

protocol UseEmailPasswordDataPassing {
  var dataStore: UseEmailPasswordDataStore? { get }
}

class UseEmailPasswordRouter: NSObject, UseEmailPasswordRoutingLogic, UseEmailPasswordDataPassing {
  var viewController: UseEmailPasswordViewController?
  var dataStore: UseEmailPasswordDataStore?
  
  // MARK: Routing

  func routeToSomewhere() {
    routeToSomewhere(segue: nil)
  }
  
  func routeToSomewhere(segue: UIStoryboardSegue?) {
    if let segue = segue {
      let destinationVC = segue.destination as! UseEmailPasswordViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataTo(&destinationDS, from: dataStore!)
    } else {
      let destinationVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "SomewhereViewController") as! UseEmailPasswordViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataTo(&destinationDS, from: dataStore!)
      viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
  }
  
  // MARK: Data Passing
  
  func passDataTo(_ destinationDS: inout UseEmailPasswordDataStore, from sourceDS: UseEmailPasswordDataStore) {
    destinationDS.attribute = sourceDS.attribute
  }
}
