//
//  UseEmailPasswordInteractor.swift
//  BiometricLogin
//
//  Created by Zaim Ramlan on 25/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UseEmailPasswordBusinessLogic {
  func UseEmailPassword(with request: UseEmailPasswordModels.UseEmailPassword.Request)
}

protocol UseEmailPasswordDataStore {
}

class UseEmailPasswordInteractor: UseEmailPasswordBusinessLogic, UseEmailPasswordDataStore {
  var worker: UseEmailPasswordWorker?
  var presenter: UseEmailPasswordPresentationLogic?
  
  // MARK: Use Case - UseEmailPassword
  
  func UseEmailPassword(with request: UseEmailPasswordModels.UseEmailPassword.Request) {
    DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(1)) {
      let response = UseEmailPasswordModels.UseEmailPassword.Response()
      self.presenter?.presentUseEmailPasswordResult(with: response)
    }
  }
}
