//
//  UseEmailPasswordPresenter.swift
//  BiometricLogin
//
//  Created by Zaim Ramlan on 25/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UseEmailPasswordPresentationLogic {
  func presentUseEmailPasswordResult(with response: UseEmailPasswordModels.UseEmailPassword.Response)
}

class UseEmailPasswordPresenter: UseEmailPasswordPresentationLogic {
  weak var viewController: UseEmailPasswordDisplayLogic?
  
  // MARK: Use Case - Use Email Password
  
  func presentUseEmailPasswordResult(with response: UseEmailPasswordModels.UseEmailPassword.Response) {
    let viewModel = UseEmailPasswordModels.UseEmailPassword.ViewModel(containsErrors: response.containsErrors)
    viewController?.displayUseEmailPasswordResult(with: viewModel)
  }
}
