//
//  UseEmailPasswordWorker.swift
//  BiometricLogin
//
//  Created by Zaim Ramlan on 25/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class UseEmailPasswordWorker {
  func UseEmailPassword(completionHandler: @escaping (Bool, String?) -> Void) {
    let isSuccessful = true
    let errorMessage: String? = "Some service error message."

    completionHandler(isSuccessful, errorMessage)
  }
}
