//
//  UseEmailPasswordModels.swift
//  BiometricLogin
//
//  Created by Zaim Ramlan on 25/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UseEmailPasswordModels {

  // MARK: Enums
  
  enum PresentationType {
    case withAnimation, withoutAnimation
  }
  
  // MARK: Use Cases
  
  enum UseEmailPassword {
    struct Request {
    }

    struct Response {
      var containsErrors: Bool?
    }

    struct ViewModel {
      var containsErrors: Bool?
    }
  }
}
