//
//  UseEmailPasswordPresenter.swift
//  BiometricLogin
//
//  Created by Zaim Ramlan on 25/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UseEmailPasswordPresentationLogic {
  func presentFetchFromDataStoreResult(with response: UseEmailPasswordModels.FetchFromDataStore.Response)
  func presentUseEmailPasswordResult(with response: UseEmailPasswordModels.UseEmailPassword.Response)
}

class UseEmailPasswordPresenter: UseEmailPasswordPresentationLogic {
  weak var viewController: UseEmailPasswordDisplayLogic?

  // MARK: Fetch Data From DataStore
  
  func presentFetchFromDataStoreResult(with response: UseEmailPasswordModels.FetchFromDataStore.Response) {
    let viewModel = UseEmailPasswordModels.FetchFromDataStore.ViewModel(userAttribute: response.userAttribute)
    viewController?.displayFetchFromDataStoreResult(with: viewModel)
  }  
  
  // MARK: Use Case - UseEmailPassword
  
  func presentUseEmailPasswordResult(with response: UseEmailPasswordModels.UseEmailPassword.Response) {
    let viewModel = UseEmailPasswordModels.UseEmailPassword.ViewModel(containsErrors: response.containsErrors, genericErrorMessage: response.genericErrorMessage, variablePassed: response.variablePassed)
    viewController?.displayUseEmailPasswordResult(with: viewModel)
  }
}
