//
//  WelcomeUserPresenter.swift
//  BiometricLogin
//
//  Created by Zaim Ramlan on 28/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeUserPresentationLogic {
  func presentWelcomeUserResult(with response: WelcomeUserModels.WelcomeUser.Response)
}

class WelcomeUserPresenter: WelcomeUserPresentationLogic {
  weak var viewController: WelcomeUserDisplayLogic?
  
  // MARK: Use Case - Welcome User
  
  func presentWelcomeUserResult(with response: WelcomeUserModels.WelcomeUser.Response) {
    let viewModel = WelcomeUserModels.WelcomeUser.ViewModel(useBiometrics: response.useBiometrics)
    viewController?.displayWelcomeUserResult(with: viewModel)
  }
}
