//
//  WelcomeUserRouter.swift
//  BiometricLogin
//
//  Created by Zaim Ramlan on 28/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeUserRoutingLogic {
  func routeToUseEmailPassword()
  func routeToUseBiometrics()
}

protocol WelcomeUserDataPassing {
  var dataStore: WelcomeUserDataStore? { get }
}

class WelcomeUserRouter: NSObject, WelcomeUserRoutingLogic, WelcomeUserDataPassing {
  var viewController: WelcomeUserViewController?
  var dataStore: WelcomeUserDataStore?
  
  // MARK: Routing
  
  func routeToUseEmailPassword() {
    let destinationVC = UIStoryboard(name: IBConstants.Storyboard.Login, bundle: nil).instantiateViewController(withIdentifier: IBConstants.ViewController.Login.UseEmailPassword)
    viewController?.navigationController?.pushViewController(destinationVC, animated: true)
  }
  
  func routeToUseBiometrics() {
    let destinationVC = UIStoryboard(name: IBConstants.Storyboard.Login, bundle: nil).instantiateViewController(withIdentifier: IBConstants.ViewController.Login.UseBiometrics)
    viewController?.navigationController?.pushViewController(destinationVC, animated: true)
  }
}
