//
//  WelcomeUserInteractor.swift
//  BiometricLogin
//
//  Created by Zaim Ramlan on 28/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftKeychainWrapper

protocol WelcomeUserBusinessLogic {
  func WelcomeUser(with request: WelcomeUserModels.WelcomeUser.Request)
}

protocol WelcomeUserDataStore {
}

class WelcomeUserInteractor: WelcomeUserBusinessLogic, WelcomeUserDataStore {
  var worker: WelcomeUserWorker?
  var presenter: WelcomeUserPresentationLogic?
  
  // MARK: Use Case - Welcome User
  
  func WelcomeUser(with request: WelcomeUserModels.WelcomeUser.Request) {
    var useBiometrics = true
    if let value = KeychainWrapper.standard.bool(forKey: KeychainConstants.User.UseBiometrics) {
      useBiometrics = value
    }
    
    let response = WelcomeUserModels.WelcomeUser.Response(useBiometrics: useBiometrics)
    presenter?.presentWelcomeUserResult(with: response)
  }
}
