//
//  DashboardHomeModels.swift
//  BiometricLogin
//
//  Created by Zaim Ramlan on 28/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DashboardHomeModels {

  // MARK: Use Cases
  
  enum FetchFromDataStore {
    struct Request {
    }
    
    struct Response {
      var biometricsType: BiometricsType
      var useBiometrics: Bool
    }
    
    struct ViewModel {
      var biometricsType: BiometricsType
      var useBiometrics: Bool
    }
  }
  
  enum ToggleUseBiometrics {
    struct Request {
      var useBiometrics: Bool
    }
    
    struct Response {
    }
    
    struct ViewModel {
    }
  }
  
  // MARK: Scene Model
  
  enum BiometricsType: String {
    case touchID = "Touch ID"
    case faceID = "Face ID"
    case none
  }
}
