//
//  DashboardHomeRouter.swift
//  BiometricLogin
//
//  Created by Zaim Ramlan on 28/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DashboardHomeRoutingLogic {
  func routeToWelcomeScreen()
}

protocol DashboardHomeDataPassing {
  var dataStore: DashboardHomeDataStore? { get }
}

class DashboardHomeRouter: NSObject, DashboardHomeRoutingLogic, DashboardHomeDataPassing {
  var viewController: DashboardHomeViewController?
  var dataStore: DashboardHomeDataStore?

  // MARK: Routing
  
  func routeToWelcomeScreen() {
    let presentingVC = viewController?.navigationController?.presentingViewController
    viewController?.navigationController?.dismiss(animated: true, completion: {
      (presentingVC as? UINavigationController)?.popToRootViewController(animated: true)
    })
  }
}
